#!/usr/bin/env python3
"""Capture notebook output cells as text files for submission evidence.

Usage: python scripts/capture_outputs.py

Generates submission/screenshots/*.txt summaries from each notebook's
executed output cells. Designed for CLI vibe-coding workflow (VIBE-CODING.md):
no manual screenshot needed — reproducible from command line.

Output:
  submission/screenshots/01_embeddings_index.txt
  submission/screenshots/02_hybrid_search_rrf.txt
  submission/screenshots/03_search_api_benchmark.txt
  submission/screenshots/04_feast_feature_store.txt
  submission/screenshots/SUMMARY.txt   (all-in-one)

Each file includes: notebook title, cell outputs (stdout, data),
and deliverable evidence checklist per rubric.md.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTEBOOKS_DIR = ROOT / "notebooks"
SCREENSHOTS_DIR = ROOT / "submission" / "screenshots"


def extract_outputs(notebook_path: Path) -> list[str]:
    """Extract text outputs from an executed .ipynb file."""
    nb = json.loads(notebook_path.read_text(encoding="utf-8"))
    lines: list[str] = []
    lines.append(f"{'=' * 70}")
    lines.append(f"  Notebook: {notebook_path.name}")
    lines.append(f"{'=' * 70}")
    lines.append("")

    for idx, cell in enumerate(nb.get("cells", [])):
        cell_type = cell.get("cell_type", "")
        source = "".join(cell.get("source", [])) if isinstance(cell.get("source"), list) else cell.get("source", "")

        # Extract title from markdown cells
        if cell_type == "markdown" and source.strip().startswith("#"):
            title = source.strip().split("\n")[0].lstrip("#").strip()
            lines.append(f"╔══ CELL {idx} — {title}")
            lines.append("")

        # Extract text outputs from code cells
        if cell_type == "code":
            outputs = cell.get("outputs", [])
            has_output = False
            for out in outputs:
                if out.get("output_type") == "stream":
                    text = "".join(out.get("text", []))
                    if text.strip():
                        if not has_output:
                            lines.append(f"┌── CELL {idx} (code)")
                            has_output = True
                        lines.append(text.rstrip())
                elif out.get("output_type") == "execute_result":
                    data = out.get("data", {})
                    text_plain = data.get("text/plain", "")
                    if isinstance(text_plain, list):
                        text_plain = "".join(text_plain)
                    if text_plain.strip():
                        if not has_output:
                            lines.append(f"┌── CELL {idx} (code)")
                            has_output = True
                        lines.append(f"  Result: {text_plain.rstrip()}")
            if has_output:
                lines.append("")

    return lines


def generate_summary(notebook_names: list[str]) -> str:
    """Generate a rubric-aligned summary referencing the specific cells."""
    return f"""======================================================================
  DAY 19 LAB — SUBMISSION EVIDENCE SUMMARY
======================================================================
  Student: Trần Đình Minh Vương (2A202600495)
  Cohort:  A20-K1 | Path: lite
  Generated by: scripts/capture_outputs.py
======================================================================

CHECKLIST (rubric.md):

NB1 — 01_embeddings_index
  ☐ Cell §4: Indexed 1000 vectors → see 01_embeddings_index.txt
  ☐ Cell §5: Top-5 results keyword query → see 01_embeddings_index.txt
  ☐ Cell §6: Paraphrase query → cloud topic cluster → see 01_embeddings_index.txt

NB2 — 02_hybrid_search_rrf
  ☐ Cell §4: Precision@10 — hybrid > keyword & semantic → see 02_hybrid_search_rrf.txt
  ☐ Cell §5: Slice by query type (exact/paraphrase/mixed) → see 02_hybrid_search_rrf.txt

NB3 — 03_search_api_benchmark
  ☐ Cell §2: API response sample → see 03_search_api_benchmark.txt
  ☐ Cell §3: Latency P50/P95/P99 table → see 03_search_api_benchmark.txt
  ☐ Cell §4: PASS — hybrid P99 < 50ms → see 03_search_api_benchmark.txt

NB4 — 04_feast_feature_store
  ☐ Cell §3: feast apply 3 views → see 04_feast_feature_store.txt
  ☐ Cell §4: materialize log → see 04_feast_feature_store.txt
  ☐ Cell §5: online lookup result → see 04_feast_feature_store.txt
  ☐ Cell §6: P50/P95/P99 < 10ms → see 04_feast_feature_store.txt
  ☐ Cell §7: PIT join DataFrame (3 rows) → see 04_feast_feature_store.txt

======================================================================
  NOTE: These .txt files are automatically captured cell outputs.
  For final submission, also include manual screenshots of Jupyter
  cells showing the same outputs with timestamps visible.
======================================================================
"""


def main() -> int:
    SCREENSHOTS_DIR.mkdir(parents=True, exist_ok=True)

    notebook_files = sorted(NOTEBOOKS_DIR.glob("0*.ipynb"))
    if not notebook_files:
        print("ERROR: No .ipynb files found in notebooks/. Run notebooks first.")
        return 1

    all_lines: list[str] = []
    for nb_path in notebook_files:
        lines = extract_outputs(nb_path)
        all_lines.extend(lines)
        all_lines.append("")

        # Write per-notebook file
        out_path = SCREENSHOTS_DIR / nb_path.with_suffix(".txt").name
        out_path.write_text("\n".join(lines), encoding="utf-8")
        print(f"  Wrote: {out_path}")

    # Write all-in-one summary
    summary_path = SCREENSHOTS_DIR / "SUMMARY.txt"
    summary = generate_summary([f.name for f in notebook_files])
    summary += "\n" + "\n".join(all_lines)
    summary_path.write_text(summary, encoding="utf-8")
    print(f"  Wrote: {summary_path}")
    print(f"\nDone. {len(notebook_files)} notebooks captured to {SCREENSHOTS_DIR}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
